# add domain specific commands here (e.g. at work)

# =========== GOOGLE EARTH ===========
# adb to path
export PATH=/usr/local/google/home/dpkay/src/dev_git5/googleclient/earth/client/thirdparty/embedded-arm-android/android-sdk-linux_x86/platform-tools:$PATH

# git tools to path
#export PATH=/usr/local/google/home/dpkay/src/dev_git5/googleclient/earth/client/thirdparty/embedded-arm-android/android-sdk-mac_x86/platform-tools:$PATH

# hammer
hammer() { /usr/local/google/home/dpkay/src/dev_git5/googleclient/earth/client/hammer.sh -j16 $@ ;}
alias hopt="hammer --mode=opt"
alias hdbg="hammer --mode=dbg"

# hammer shortcuts
alias hammer-android-opt="hammer --mode=android-arm-opt kalee"

gearth() { g -R $@ ~/src/dev_git5/googleclient ;}

killearth() {
  pkill -9 googleearth-bin;
  rm /usr/local/google/home/dpkay/.googleearth/instance-running-lock;
}
