# change this
export HOME_DIR=/home/dpkay

# you should not need to change this
export HOME_DIR_LOCAL=`pwd`
export UNIXCONFIG=$HOME_DIR/unixconfig
source "$UNIXCONFIG/bashrc"
source "$UNIXCONFIG/alias_bash"
